const data = [
	// thanks syce!!!!
	//
    //{
    //    name: "Example",
	//    id: "example",
    //    description: "Example",
    //    link: "game/example.html",
	//	  devices: "PC, Mobile",
	//	  unblocked: "yes",
    //},
	{
        name: "Breakout",
		id: "breakout",
        description: "shoot ball at brick",
        link: "https://html5.gamedistribution.com/8f006852782547a7b8dbf392f7883e9e/",
		devices: "PC, Mobile",
		unblocked: "no",
    },
    {
        name: "Donkey Kong",
		id: "donkeykong",
        description: "climb thing and defeat evil monkey",
        link: "https://freekong.org/",
		devices: "PC",
		unblocked: "no",
    },
	{
        name: "Duck Hunt",
		id: "duckhunt",
        description: "shoot duck",
        link: "https://www.retrogames.cc/embed/21039-duck-hunt-world.html",
		devices: "PC, Mobile",
		unblocked: "no",
    },
	{
        name: "Invaders",
		id: "invaders",
        description: "shoot alien things",
        link: "game/invaders.html",
		devices: "PC",
		unblocked: "yes",
    },
	{
        name: "Pacman",
		id: "pacman",
        description: "eat yummy dot",
        link: "https://bward2.github.io/pacman-js/",
		devices: "PC",
		unblocked: "no",
    },
	{
        name: "Pong",
		id: "pong",
        description: "pong",
        link: "game/pong.html",
		devices: "PC, Mobile",
		unblocked: "yes",
    },
	{
        name: "Q*bert",
		id: "qbert",
        description: "orange man does funny stuff with weird controls",
        link: "https://freeqbert.org/",
		devices: "PC",
		unblocked: "no",
    },
	{
        name: "Snake",
		id: "snake",
        description: "snek",
        link: "game/snake.html",
		devices: "PC",
		unblocked: "yes",
    },
	{
        name: "Tetris",
		id: "tetris",
        description: "tetris!!!! btw press enter for instant drop",
        link: "game/tetris.html",
		devices: "PC",
		unblocked: "yes",
    },
	{
        name: "Getting Over It",
		id: "gettingoverit",
        description: "🤬",
        link: "game/iframe/gettingoverit/index.html",
		devices: "PC, Mobile",
		unblocked: "yes",
    },
	{
        name: "Geometry Dash",
		id: "geometrydash",
        description: "robert topala",
        link: "game/geometrydash.html",
		devices: "PC, Mobile",
		unblocked: "yes",
    },
	{
		name: "Adventure Capitalist",
		id: "adventurecapitalist",
		description: "Adventure Capitalist is a game where you can form your own multi-national conglomerate to create a world-wide, monopolistic economy.",
		link: "https://than1089.github.io/adventure-capitalist/",
		devices: "PC, Mobile",
		unblocked: "no",
    },
    {
		name: "2048",
		id: "2048",
		description: "In this game, you're trying to slide the number tiles on the grid to combine them to create a tile with the number 2048. Can you go beyond 2048?",
		link: "game/iframe/2048/index.html",
		devices: "PC, Mobile",
		unblocked: "yes",
    },
];